AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Iris MVP - application stack (Lambda functions + wiring).

Parameters:
  Stage:
    Type: String
    Default: prod
    AllowedValues:
      - prod
  InfraStackName:
    Type: String
    Default: iris-infra-prod
  ReminderDelaySeconds:
    Type: Number
    Default: 7200

Globals:
  Function:
    Runtime: python3.12
    Architectures:
      - arm64
    MemorySize: 256
    Timeout: 20
    Tracing: Active
    Tags:
      Stage: !Ref Stage

Resources:
  IrisInviteFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Preserve existing physical name during import.
      FunctionName: iris-prod-IrisInviteFunction-mWTN1LXzwlBP
      CodeUri: src/
      Handler: app.lambda_handler
      Role: !ImportValue
        'Fn::Sub': '${InfraStackName}-InviteFunctionRoleArn'

      EphemeralStorage:
        Size: 512

      Environment:
        Variables:
          BUCKET_NAME: !ImportValue
            'Fn::Sub': '${InfraStackName}-RawEmailBucketName'
          TABLE_NAME: !ImportValue
            'Fn::Sub': '${InfraStackName}-ThreadsTableName'
          SCHEDULER_ROLE_ARN: !ImportValue
            'Fn::Sub': '${InfraStackName}-SchedulerInvokeRoleArn'
          SCHEDULER_GROUP_NAME: !ImportValue
            'Fn::Sub': '${InfraStackName}-ReminderScheduleGroupName'
          REMINDER_DELAY_SECONDS: !Ref ReminderDelaySeconds
          REMINDER_LAMBDA_ARN: !GetAtt IrisReminderFunction.Arn
          GOOGLE_OAUTH_SECRET_NAME: liazon/iris/google_oauth
          AI_REASONING_MODE: 'true'
          IRIS_EMAIL: iris@liazon.cc
          TIMEZONE: America/New_York
          BEDROCK_GUARDRAIL_ID: 4us43pe9ntte
          BEDROCK_GUARDRAIL_VERSION: DRAFT
          BEDROCK_REGION: us-east-1

  # Allow SES receipt rules to invoke this Lambda.
  # NOTE: This does not create SES rules; it only permits invocation from the existing rule ARN.
  AllowSesInvokeLambdaFromReceiptRule:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IrisInviteFunction
      Principal: ses.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:receipt-rule-set/iris-${Stage}:receipt-rule/iris-inbound

  IrisReminderFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Stack-managed name; ensures GitHub Actions / SAM deployments own this Lambda.
      FunctionName: liazon-reminder-handler
      CodeUri: src/
      Handler: iris.entrypoints.reminder_handler.lambda_handler
      Role: !ImportValue
        'Fn::Sub': '${InfraStackName}-ReminderFunctionRoleArn'

      EphemeralStorage:
        Size: 512

      Environment:
        Variables:
          THREADS_TABLE: !ImportValue
            'Fn::Sub': '${InfraStackName}-ThreadsTableName'
          IRIS_EMAIL: iris@liazon.cc
          TIMEZONE: America/New_York
          REMINDER_DELAY_SECONDS: !Ref ReminderDelaySeconds

Outputs:
  InviteFunctionName:
    Value: !Ref IrisInviteFunction
  InviteFunctionArn:
    Value: !GetAtt IrisInviteFunction.Arn

  ReminderFunctionName:
    Value: !Ref IrisReminderFunction
  ReminderFunctionArn:
    Value: !GetAtt IrisReminderFunction.Arn
