AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Iris MVP - infrastructure stack (stateful resources + stable IAM roles).

Parameters:
  Stage:
    Type: String
    Default: prod
    AllowedValues:
      - prod

Resources:
  IrisRawEmailBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Stage
          Value: !Ref Stage

  IrisThreadsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: threadId
          AttributeType: S
      KeySchema:
        - AttributeName: threadId
          KeyType: HASH
      Tags:
        - Key: Stage
          Value: !Ref Stage

  IrisInviteFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: IrisInviteFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource: !Sub ${IrisRawEmailBucket.Arn}/*
              - Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:ConditionCheckItem
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource:
                  - !GetAtt IrisThreadsTable.Arn
                  - !Sub ${IrisThreadsTable.Arn}/index/*
              - Effect: Allow
                Action:
                  - ses:SendRawEmail
                Resource: "*"
      Tags:
        - Key: Stage
          Value: !Ref Stage

  IrisReminderFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: IrisReminderFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:ConditionCheckItem
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource:
                  - !GetAtt IrisThreadsTable.Arn
                  - !Sub ${IrisThreadsTable.Arn}/index/*
              - Effect: Allow
                Action:
                  - ses:SendRawEmail
                Resource: "*"
      Tags:
        - Key: Stage
          Value: !Ref Stage

Outputs:
  RawEmailBucketName:
    Value: !Ref IrisRawEmailBucket
    Export:
      Name: !Sub ${AWS::StackName}-RawEmailBucketName

  ThreadsTableName:
    Value: !Ref IrisThreadsTable
    Export:
      Name: !Sub ${AWS::StackName}-ThreadsTableName

  InviteFunctionRoleArn:
    Value: !GetAtt IrisInviteFunctionRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-InviteFunctionRoleArn

  ReminderFunctionRoleArn:
    Value: !GetAtt IrisReminderFunctionRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ReminderFunctionRoleArn
