AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Iris MVP - inbound email (SES -> S3) processing + DynamoDB thread tracking + outbound calendar invite (SES).
  This stack intentionally does NOT create/manage SES receipt rule sets/rules or the S3 bucket policy, because
  those resources already exist and are managed outside this stack.

Globals:
  Function:
    Runtime: python3.12
    Architectures:
      - arm64
    MemorySize: 256
    Timeout: 20
    Tracing: Active

Resources:
  IrisRawEmailBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  IrisThreadsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: threadId
          AttributeType: S
      KeySchema:
        - AttributeName: threadId
          KeyType: HASH

  IrisInviteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler

      EphemeralStorage:
        Size: 512

      Environment:
        Variables:
          BUCKET_NAME: !Ref IrisRawEmailBucket
          TABLE_NAME: !Ref IrisThreadsTable
          IRIS_EMAIL: iris@liazon.cc
          TIMEZONE: America/New_York
          BEDROCK_GUARDRAIL_ID: 4us43pe9mtte
          BEDROCK_GUARDRAIL_VERSION: DRAFT
          BEDROCK_REGION: us-east-1

      Policies:
        # Read the raw MIME email from S3
        - S3ReadPolicy:
            BucketName: !Ref IrisRawEmailBucket

        # Write/read thread state in DynamoDB
        - DynamoDBCrudPolicy:
            TableName: !Ref IrisThreadsTable

        # Send outbound invites via SES (SendRawEmail has no resource-level ARN; must be "*")
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendRawEmail
              Resource: "*"

  # Allow SES receipt rules to invoke this Lambda.
  # NOTE: This does not create SES rules; it only permits invocation from the existing rule ARN.
  AllowSesInvokeLambdaFromReceiptRule:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IrisInviteFunction
      Principal: ses.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:receipt-rule-set/iris-prod:receipt-rule/iris-inbound

Outputs:
  RawEmailBucketName:
    Value: !Ref IrisRawEmailBucket
  ThreadsTableName:
    Value: !Ref IrisThreadsTable
  InviteFunctionName:
    Value: !Ref IrisInviteFunction
  InviteFunctionArn:
    Value: !GetAtt IrisInviteFunction.Arn
