AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Iris MVP - SES inbound processor + calendar invite sender (PoC)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Tracing: Active

Parameters:
  Environment:
    Type: String
    Default: prod

Mappings: {}

Resources:
  IrisRawEmailBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      # IMPORTANT: do NOT set BucketName unless it exactly matches the existing bucket CFN created
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: iris-mvp
        - Key: Environment
          Value: !Ref Environment

  IrisThreadsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      # IMPORTANT: do NOT set TableName unless it exactly matches the existing table CFN created
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      Tags:
        - Key: Project
          Value: iris-mvp
        - Key: Environment
          Value: !Ref Environment

  IrisInviteFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      # IMPORTANT: no RoleName => avoids CAPABILITY_NAMED_IAM and avoids replacement risk
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: IrisInviteFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource:
                  - !Sub "${IrisRawEmailBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                Resource: !GetAtt IrisThreadsTable.Arn
              - Effect: Allow
                Action: ses:SendRawEmail
                Resource: "*"
      Tags:
        - Key: Project
          Value: iris-mvp
        - Key: Environment
          Value: !Ref Environment

  IrisInviteFunction:
    Type: AWS::Serverless::Function
    Properties:
      # IMPORTANT: do NOT set FunctionName unless it exactly matches the existing lambda CFN created
      CodeUri: src/
      Handler: app.lambda_handler
      Role: !GetAtt IrisInviteFunctionRole.Arn
      Environment:
        Variables:
          RAW_BUCKET_NAME: !Ref IrisRawEmailBucket
          THREADS_TABLE_NAME: !Ref IrisThreadsTable
      Tags:
        Project: iris-mvp
        Environment: !Ref Environment

  AllowSesInvokeLambdaFromReceiptRule:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IrisInviteFunction
      Action: lambda:InvokeFunction
      Principal: ses.amazonaws.com
      StatementId: AllowSesInvokeFromReceiptRuleV2
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:receipt-rule-set/iris-prod:receipt-rule/iris-inbound"

  AllowSesInvokeLambdaFromRuleSet:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IrisInviteFunction
      Action: lambda:InvokeFunction
      Principal: ses.amazonaws.com
      StatementId: AllowSesInvokeFromRuleSetV2
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:receipt-rule-set/iris-prod"

Outputs:
  RawEmailBucketName:
    Value: !Ref IrisRawEmailBucket
  ThreadsTableName:
    Value: !Ref IrisThreadsTable
  InviteFunctionName:
    Value: !Ref IrisInviteFunction
