AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Iris MVP - SES inbound processor + calendar invite sender (PoC)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Tracing: Active

Resources:
  # --------------------------
  # Storage (matches live)
  # --------------------------
  IrisRawEmailBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: iris-prod-irisrawemailbucket-jm8b0udtvnuv
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  IrisThreadsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: iris-prod-IrisThreadsTable-FXJL2M8UM2N6
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

  # --------------------------
  # IAM (no RoleName => no CAPABILITY_NAMED_IAM)
  # --------------------------
  IrisInviteFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # Basic logging
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: IrisInviteFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Read raw email from S3 (SES stores it there)
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub "${IrisRawEmailBucket.Arn}/*"

              # Write thread/metadata to DynamoDB
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                Resource: !GetAtt IrisThreadsTable.Arn

              # Send the outbound invite (RAW)
              # (You can tighten this later; keep it simple for PoC)
              - Effect: Allow
                Action:
                  - ses:SendRawEmail
                Resource: "*"

  # --------------------------
  # Lambda (matches live name)
  # --------------------------
  IrisInviteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: iris-prod-IrisInviteFunction-mWTN1LXzwlBP
      CodeUri: src/
      Handler: app.lambda_handler
      Role: !GetAtt IrisInviteFunctionRole.Arn
      Environment:
        Variables:
          RAW_BUCKET_NAME: !Ref IrisRawEmailBucket
          THREADS_TABLE_NAME: !Ref IrisThreadsTable
          # If you use these in app.py, keep them here:
          # FROM_ADDRESS: iris@liazon.cc

  # --------------------------
  # SES -> Lambda invoke permissions (CFN-managed)
  # These are SAFE to manage in CFN.
  # --------------------------
  AllowSesInvokeLambdaFromReceiptRule:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IrisInviteFunction
      Action: lambda:InvokeFunction
      Principal: ses.amazonaws.com
      StatementId: AllowSesInvokeFromReceiptRuleV1
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:receipt-rule-set/iris-prod:receipt-rule/iris-inbound"

  AllowSesInvokeLambdaFromRuleSet:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IrisInviteFunction
      Action: lambda:InvokeFunction
      Principal: ses.amazonaws.com
      StatementId: AllowSesInvokeFromRuleSetV1
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:receipt-rule-set/iris-prod"

Outputs:
  RawEmailBucketName:
    Value: !Ref IrisRawEmailBucket
  ThreadsTableName:
    Value: !Ref IrisThreadsTable
  InviteFunctionName:
    Value: !Ref IrisInviteFunction
