AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Iris MVP - inbound email -> S3 raw -> Lambda -> reply-all w/ ICS + DynamoDB idempotency

Parameters:
  IrisEmail:
    Type: String
    Default: iris@liazon.cc
    Description: The inbound recipient Iris listens for (and the From address Iris uses for outbound).

  ReceiptRuleSetName:
    Type: String
    Default: iris-prod-cfn
    Description: SES receipt rule set managed by CloudFormation (use a distinct name to avoid collisions with any manually created rule set).

  ReceiptRuleName:
    Type: String
    Default: iris-inbound
    Description: SES receipt rule name.

  RawEmailPrefix:
    Type: String
    Default: raw/
    Description: S3 key prefix for inbound raw emails.

Globals:
  Function:
    Runtime: python3.12
    Timeout: 20
    MemorySize: 256

Resources:
  # Keep these minimal to match the existing deployed stack and avoid replacements.
  IrisRawEmailBucket:
    Type: AWS::S3::Bucket
    Metadata:
      SamResourceId: IrisRawEmailBucket

  IrisThreadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
    Metadata:
      SamResourceId: IrisThreadsTable

  IrisInviteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Environment:
        Variables:
          BUCKET_NAME: !Ref IrisRawEmailBucket
          TABLE_NAME: !Ref IrisThreadsTable
          IRIS_EMAIL: !Ref IrisEmail
          TIMEZONE: America/New_York
          DEFAULT_START_HOUR: '13'
          DEFAULT_DURATION_MINUTES: '30'
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref IrisRawEmailBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref IrisThreadsTable
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendRawEmail
              Resource: '*'

  # ---- SES inbound (new, CloudFormation-managed) ----

  IrisReceiptRuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Properties:
      RuleSetName: !Ref ReceiptRuleSetName

  # Allow SES to store the raw email object in S3 under RawEmailPrefix
  IrisRawEmailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref IrisRawEmailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSESPutObject
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action:
              - s3:PutObject
            Resource: !Sub arn:aws:s3:::${IrisRawEmailBucket}/${RawEmailPrefix}*
            Condition:
              StringEquals:
                aws:Referer: !Ref AWS::AccountId

  # Allow SES to invoke the Lambda (rule-set level)
  AllowSesInvokeLambdaRuleSet:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IrisInviteFunction
      Principal: ses.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:receipt-rule-set/${ReceiptRuleSetName}

  # Allow SES to invoke the Lambda (rule-level; some setups evaluate this ARN)
  AllowSesInvokeLambdaRule:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IrisInviteFunction
      Principal: ses.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:receipt-rule-set/${ReceiptRuleSetName}:receipt-rule/${ReceiptRuleName}

  IrisInboundReceiptRule:
    Type: AWS::SES::ReceiptRule
    DependsOn:
      - IrisReceiptRuleSet
      - IrisRawEmailBucketPolicy
      - AllowSesInvokeLambdaRuleSet
      - AllowSesInvokeLambdaRule
    Properties:
      RuleSetName: !Ref ReceiptRuleSetName
      Rule:
        Name: !Ref ReceiptRuleName
        Enabled: true
        ScanEnabled: true
        TlsPolicy: Optional
        Recipients:
          - !Ref IrisEmail
        Actions:
          - S3Action:
              BucketName: !Ref IrisRawEmailBucket
              ObjectKeyPrefix: !Ref RawEmailPrefix
          - LambdaAction:
              FunctionArn: !GetAtt IrisInviteFunction.Arn
              InvocationType: Event
          - StopAction:
              Scope: RuleSet

Outputs:
  RawEmailBucketName:
    Value: !Ref IrisRawEmailBucket
  ThreadsTableName:
    Value: !Ref IrisThreadsTable
  InviteFunctionName:
    Value: !Ref IrisInviteFunction
  ReceiptRuleSetName:
    Value: !Ref ReceiptRuleSetName
  ReceiptRuleName:
    Value: !Ref ReceiptRuleName
